warehouse:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: 192.168.1.39
      port: 5432
      user: etl
      pass: demopass
      dbname: adventureworks
      schema: public

  target: dev

